http:
  connections:
    maxTotal: 32
    defaultMaxPerRoute: 8
    evictionDelayInMillis: 5000
    idleTimeOutInSeconds: 30
concurrency:
  corePoolSize: 8
spring:
  data:
    elasticsearch:
      cluster-name: web-crawler
      cluster-nodes: 127.0.0.1:9300

